org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric / Minecraft
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.156.0+26.2

# Mod
mod_version=0.1.0-alpha.15
maven_group=org.evgenium.speedrun
archives_base_name=Evgenium_SpeedRun
